name: Update Latest Tag

on:
  release:
    types: [published]
  workflow_dispatch:  # Allows manual execution

jobs:
  update-latest-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch tags
        run: git fetch --tags

      - name: Delete existing latest tag (if exists)
        run: |
          if git rev-parse latest >/dev/null 2>&1; then
            git tag -d latest
            git push origin --delete latest || true
          fi

      - name: Create and push new latest tag
        run: |
          git tag latest ${{ github.sha }}
          git push origin latest
